#!/bin/sh
# -------
# File:        aurex-unplugged-theme
# Description: switch background theme
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") {enable|disable}"
}

ACTION="$1"
[ "$ACTION" ] || usage

case "$ACTION" in
	enable)
		aurex-transmute --module=unplugged-theme transmute || true
		;;
	disable)
		aurex-transmute --module=unplugged-theme untransmute || true
		;;
	*)
		usage
		;;
esac

exit 0
