#!/bin/sh
set -e
WORK_DIR="$(dirname "$0")"

case "$1" in
	clean)
		rm -rf $WORK_DIR/install
		;;
	*)
		mkdir -p $WORK_DIR/install
		for F in $WORK_DIR/../*png ; do
			cp "$F" $WORK_DIR/install
		done
		# overrides
		MBOX_FILE="aurex-logos/aurex-mdm-theme.xcf"
		BG_FILE="wallpapers/aurex-golden-ratio.xcf"
		xcf2png "$BG_FILE" "fondo0" "fondo1" > $WORK_DIR/install/background.png
		xcf2png "$MBOX_FILE" > $WORK_DIR/install/main_box.png
		cp $WORK_DIR/*.desktop $WORK_DIR/*.xml $WORK_DIR/install/
		;;
esac

exit 0

