#!/bin/sh
set -e
WORK_DIR="$(dirname "$0")"

case "$1" in
	clean)
		rm -rf $WORK_DIR/install
		;;
	*)
		mkdir -p $WORK_DIR/install
		for F in $WORK_DIR/../*png ; do
			cp "$F" $WORK_DIR/install
		done
		# overrides
		MDM_FILE="aurex-logos/aurex-mdm-simply"
		xcf2png "$MDM_FILE" > $WORK_DIR/install/bg.png
#		for f in text.png main_box.png ; do
#			xcf2png -C "$MDM_FILE" "$f" > $WORK_DIR/install/$f
#		done
		cp $WORK_DIR/*.desktop $WORK_DIR/*.xml $WORK_DIR/install/
		;;
esac

exit 0

