#! /bin/sh
### BEGIN INIT INFO
# Provides:          mdm
# Should-Start:      console-screen kbd acpid dbus hal network-manager
# Required-Start:    $local_fs $remote_fs x11-common
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MDM Display Manager
# Description:       Debian init script for the MDM Display Manager
### END INIT INFO
#
# Author:       Luis Garcia <luisgg@gmail>
#

set -e
cat <<EOF
Warning!!!!!
This is just an useless dummy script and it does NOTHING AT ALL about the mdm display manager.
Please use
	/etc/init.d/aurex-mdm $1
instead !!!!

In aurex, mdm has been converted to upstart, and the service name is aurex-mdm
you can use the service command or the /etc/init.d/aurex-mdm link to manage the service
EOF
exit 0
