#!/bin/sh
set -e
WORK_DIR="$(dirname "$0")"

case "$1" in
	clean)
		rm -rf $WORK_DIR/install
		;;
	*)
		mkdir $WORK_DIR/install
		for F in $WORK_DIR/*.png $WORK_DIR/README $WORK_DIR/*.plymouth $WORK_DIR/*.script ; do
			f="$(basename "$F")"
			fxcf="$(basename "$F" ".png").xcf"
			if [ -r "$WORK_DIR/aurex/$f" ] ; then
				FF="$WORK_DIR/aurex/$f"
			elif [ -r "$WORK_DIR/aurex/$fxcf" ] ; then
				xcf2png "$WORK_DIR/aurex/$fxcf" > $WORK_DIR/install/$f.png
			elif [ -r "$F" ] ; then
				FF="$F"
			fi
		done
		cp $WORK_DIR/aurex/*.script $WORK_DIR/aurex/*plymouth $WORK_DIR/README* $WORK_DIR/aurex/README* $WORK_DIR/install/
		;;
esac

exit 0

